In [1]:
#importing relevant libraries
import numpy as np 
import pandas as pd

In [3]:
#Importing the data
cmpy_info = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\company_info.csv')
mrkt_indices = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\market_indices.csv')
stk_prices = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\stock_prices.csv')
stk_prices_indicators = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\stock_prices_with_indicators.csv')

In [4]:
#Exploring company information 
cmpy_info.head()

   ticker company_name      sector    ipo_date
0  STK001     TechCorp  Technology  2021-04-10
1  STK002  DataSystems  Technology  2016-10-12
2  STK003    CloudNine  Technology  2016-01-18
3  STK004  CyberShield  Technology  2022-02-21
4  STK005    MediPharm  Healthcare  2018-03-05

In [5]:
cmpy_info.shape

(20, 4)

In [6]:
cmpy_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ticker        20 non-null     object
 1   company_name  20 non-null     object
 2   sector        20 non-null     object
 3   ipo_date      20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

In [7]:
mrkt_indices.head()

,date,sp500_close,nasdaq_close,vix_close,treasury_10y,dollar_index,market_regime
0,2021-01-04,3891.04,12952.02,20.48,1.496,90.07,bull
1,2021-01-05,3847.20,13116.52,19.89,1.504,90.73,bull
2,2021-01-06,3878.24,12818.48,20.02,1.507,90.46,bull
3,2021-01-07,3803.95,13290.11,19.59,1.498,90.67,bull
4,2021-01-08,3715.64,13365.73,20.14,1.498,90.64,bull

In [8]:
mrkt_indices.shape

(780, 7)

In [9]:
mrkt_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           780 non-null    object
 1   sp500_close    780 non-null    float64
 2   nasdaq_close   780 non-null    float64
 3   vix_close      780 non-null    float64
 4   treasury_10y   780 non-null    float64
 5   dollar_index   780 non-null    float64
 6   market_regime  780 non-null    object
dtypes: float64(5), object(2)
memory usage: 42.8+ KB

In [10]:
stk_prices.head()

   ticker        date    open    high     low   close   volume  adjusted_close
0  STK001  2021-01-04  158.09  160.97  158.09  160.11   962644          160.11
1  STK001  2021-01-05  163.16  165.50  160.76  162.36  1312685          162.36
2  STK001  2021-01-06  161.89  162.51  160.94  161.78  1449177          161.78
3  STK001  2021-01-07  163.33  167.90  163.33  167.07  1534833          167.07
4  STK001  2021-01-08  168.20  168.20  164.12  165.68   848261          165.68

In [12]:
stk_prices.shape

(15600, 8)

In [13]:
stk_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15600 entries, 0 to 15599
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ticker          15600 non-null  object
 1   date            15600 non-null  object
 2   open            15600 non-null  float64
 3   high            15600 non-null  float64
 4   low             15600 non-null  float64
 5   close           15600 non-null  float64
 6   volume          15600 non-null  int64
 7   adjusted_close  15600 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 975.1+ KB

In [14]:
stk_prices_indicators.head()

,ticker,date,open,high,low,close,volume,adjusted_close,sma_20,sma_50,...,true_range,atr_14,volume_sma_20,volume_ratio,momentum_10,momentum_20,price_to_sma_50,volatility_20,future_return_5d,trend_label
0,STK001,2021-01-04,158.09,160.97,158.09,160.11,962644.0,160.11,160.110000,160.110000,...,2.88,2.880,962644.00,1.000000,NaN,NaN,0.000000,NaN,0.026357,Uptrend
1,STK001,2021-01-05,163.16,165.50,160.76,162.36,1312685.0,162.36,161.235000,161.235000,...,5.39,4.135,1137664.50,1.153842,NaN,NaN,0.006977,NaN,0.018169,Sideways
2,STK001,2021-01-06,161.89,162.51,160.94,161.78,1449177.0,161.78,161.416667,161.416667,...,1.57,3.280,1241502.00,1.167277,NaN,NaN,0.002251,0.012463,-0.012301,Sideways
3,STK001,2021-01-07,163.33,167.90,163.33,167.07,1534833.0,167.07,162.830000,162.830000,...,6.12,3.990,1314834.75,1.167320,NaN,NaN,0.026039,0.018138,-0.061950,Downtrend
4,STK001,2021-01-08,168.20,168.20,164.12,165.68,848261.0,165.68,163.400000,163.400000,...,4.08,4.008,1221520.00,0.694431,NaN,NaN,0.013953,0.018663,-0.070196,Downtrend

In [15]:
stk_prices_indicators.shape

(15502, 31)

In [16]:
stk_prices_indicators.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15502 entries, 0 to 15501
Data columns (total 31 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticker            15502 non-null  object
 1   date              15502 non-null  object
 2   open              15502 non-null  float64
 3   high              15502 non-null  float64
 4   low               15502 non-null  float64
 5   close             15502 non-null  float64
 6   volume            15502 non-null  float64
 7   adjusted_close    15502 non-null  float64
 8   sma_20            15192 non-null  float64
 9   sma_50            15502 non-null  float64
 10  sma_200           15502 non-null  float64
 11  ema_12            15502 non-null  float64
 12  ema_26            15502 non-null  float64
 13  macd              15191 non-null  float64
 14  macd_signal       15502 non-null  float64
 15  macd_histogram    15502 non-null  float64
 16  rsi_14            15172 non-null  float64
 17  bb_middle         15502 non-null  float64
 18  bb_upper          15482 non-null  float64
 19  bb_lower          15482 non-null  float64
 20  bb_width          15171 non-null  float64
 21  true_range        15502 non-null  float64
 22  atr_14            15502 non-null  float64
 23  volume_sma_20     15502 non-null  float64
 24  volume_ratio      15192 non-null  float64
 25  momentum_10       15302 non-null  float64
 26  momentum_20       15102 non-null  float64
 27  price_to_sma_50   15502 non-null  float64
 28  volatility_20     15462 non-null  float64
 29  future_return_5d  15502 non-null  float64
 30  trend_label       15502 non-null  object
dtypes: float64(28), object(3)
memory usage: 3.7+ MB

### All three data sets loaded successfully. The highest dimensionality is observed in the dataset with the stock prices and their various indicators. This is the main dataset for the analysis. Per dimension however, the stock prices data is the largest.