In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

In [3]:
#loading dataset
cmpy_info = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\company_info.csv')
mrkt_indices = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\market_indices.csv')
stk_prices = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\stock_prices.csv')
stk_prices_indicators = pd.read_csv(r'C:\Users\ofori\OneDrive\Desktop\Stock_Market_Analysis\Stock-analysis\data\stock_prices_with_indicators.csv')

In [4]:
#checking for nulls in the company information dataset
cmpy_info.isnull().sum()

ticker          0
company_name    0
sector          0
ipo_date        0
dtype: int64

#### There are no nulls in this data.

In [8]:
print(cmpy_info.duplicated().sum())

0

##### No duplicates can be observed either in the dataset

In [5]:
cmpy_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ticker        20 non-null     object
 1   company_name  20 non-null     object
 2   sector        20 non-null     object
 3   ipo_date      20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

In [6]:
cmpy_info.head()

   ticker company_name      sector    ipo_date
0  STK001     TechCorp  Technology  2021-04-10
1  STK002  DataSystems  Technology  2016-10-12
2  STK003    CloudNine  Technology  2016-01-18
3  STK004  CyberShield  Technology  2022-02-21
4  STK005    MediPharm  Healthcare  2018-03-05

In [9]:
#Transforming the IPO date feature into the right format
cmpy_info['ipo_date'] = pd.to_datetime(cmpy_info['ipo_date'])

In [10]:
#Date is now in the right format
cmpy_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ticker        20 non-null     object
 1   company_name  20 non-null     object
 2   sector        20 non-null     object
 3   ipo_date      20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 772.0+ bytes

In [11]:
mrkt_indices.isnull().sum()

date             0
sp500_close      0
nasdaq_close     0
vix_close        0
treasury_10y     0
dollar_index     0
market_regime    0
dtype: int64

##### There are no nulls in the market indices dataset.

In [12]:
mrkt_indices.duplicated().any()

np.False_

##### There are no duplicates in the market indices as well.

In [13]:
mrkt_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           780 non-null    object
 1   sp500_close    780 non-null    float64
 2   nasdaq_close   780 non-null    float64
 3   vix_close      780 non-null    float64
 4   treasury_10y   780 non-null    float64
 5   dollar_index   780 non-null    float64
 6   market_regime  780 non-null    object
dtypes: float64(5), object(2)
memory usage: 42.8+ KB

In [14]:
#Changing the date column to the right format
mrkt_indices.date = pd.to_datetime(mrkt_indices.date)

In [15]:
mrkt_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           780 non-null    datetime64[ns]
 1   sp500_close    780 non-null    float64
 2   nasdaq_close   780 non-null    float64
 3   vix_close      780 non-null    float64
 4   treasury_10y   780 non-null    float64
 5   dollar_index   780 non-null    float64
 6   market_regime  780 non-null    object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 42.8+ KB

##### The date column is now in the correct format.

In [16]:
stk_prices.head()

   ticker        date    open    high     low   close   volume  adjusted_close
0  STK001  2021-01-04  158.09  160.97  158.09  160.11   962644          160.11
1  STK001  2021-01-05  163.16  165.50  160.76  162.36  1312685          162.36
2  STK001  2021-01-06  161.89  162.51  160.94  161.78  1449177          161.78
3  STK001  2021-01-07  163.33  167.90  163.33  167.07  1534833          167.07
4  STK001  2021-01-08  168.20  168.20  164.12  165.68   848261          165.68

In [17]:
stk_prices.isnull().sum()

ticker            0
date              0
open              0
high              0
low               0
close             0
volume            0
adjusted_close    0
dtype: int64